<<<<<<< Updated upstream
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
=======
import Navbar from 'components/Navbar'
import { NextPage } from 'next'
import Head from 'next/head'
import Provider from 'context/provider'
import Tasks from 'components/Tasks'

const Home: NextPage = () => (
    <Provider>
      <Head>
        <title>Task tracker</title>
      </Head>
      <Navbar />
      <main>
        <div className="relative">
          <div className="absolute w-full -top-14 md:-top-6 lg:-top-16">
            <div className="grid grid-cols-2 mb-5 mx-16 mt-20 divide-x">
              <div>
                <h3 className="text-base text-neutral-900 text-center font-bold mb-6">
                  Incomplete
                </h3>
                <Tasks status='incomplete'/>
              </div>
              <div>
                <h3 className="text-base text-neutral-900 text-center font-bold mb-6">
                  Completed
                </h3>
                <Tasks status='completed'/>
              </div>
            </div>
          </div>
        </div>
      </main>
    </Provider>
  )

 

export default Home
>>>>>>> Stashed changes
